### ISSUE TITLE
Unify clicked square events into single function

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#69]
Currently, there are many instances of clicked square and unclicked square functions which all read more or less the same. Refactor the code so that the clicked square code is not repeated and can be called from separate parts of the dApp

**Comment by gshorer97** [comment]
- [ ] Step 1: Separate square handling code from blockchain code, have square handling in own context
- [ ] Step 2: See if we can define the CSS properties of chosen and unchosen squares more globally

**Comment by emilioziniades** [comment]
I was working on issue #82 , but I think I may have inadvertently addressed this issue. The repeated code was the jQuery calls. I have now made use of styled-components to set the square border colour. Like this

```
const gridItem = styled.button`
      background: ${props => props.colour};
      border: ${props => props.selected ? '2px solid' + props.inverseColour : 'none'};
`
```

Now, all the `handleClick` functions (in `square` , `eventRow`, and `eventToast`  simply `setSelectedSquare` . I think this is a pretty neat fix. You can see these changes in commit 7a5601a5e4c98092f21f035ed9f5fb80f9f6dd4c

However, I am keeping this issue open, because `handleSquare` is still problematic.

**Comment by gshorer97** [comment]
Awesome! This is the elegant solution I was looking for. Will keep an eye out for any bugs

**Comment by emilioziniades** [comment]
`handleSquare` now works as of commit 1db26b218b1407d744b442261045a8ac31b62850 . Am going to close this issue.
