### ISSUE TITLE
Inverted colour should update on colour change

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#82]
When claiming/changing colour the selected square's inverted border is not updated to reflect the new inverted colour

**Comment by emilioziniades** [comment]
Good catch. I have fixed this in commit 818d32394ec5bb77c73c7c17924669cf5bb76583.

The problem was that the jquery sets the border colour once, and does not update when square colour changes. You could make a new jquery call when colour changes, but that seemed overkill. Rather, I eliminated the need for jquery by implementing the functionality in gridItem using styled components.

In general,styled-components are pretty powerful: you can pass props to a component which determine its style. I think eventually we should try eliminate all instances of jquery, and try implement the same functionality in styled-components.

Closing this issue though because the bug is fixed now.
