### ISSUE TITLE
Ability to view explainer while account is connected

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#87]
Currently if a user visits the explainer they are not able to connect their account. Additionally, if they are connected and visit the explainer they will lose their connection.

There should be harmony across the site so that a user can connect and stay connected whether on the explainer or the main page

**Comment by emilioziniades** [comment]
Yeah, totally agreed. It raises a really interesting point, because what it would require is basically lifting state up so that both pages of the site can see the blockchain state. 

From an initial glance, this is very possible using Gatsby. Check out this [article](https://levelup.gitconnected.com/keeping-state-between-pages-with-local-state-in-gatsby-js-96f8583e0db2). Basically, you wrap both pages in the same wrapper, and this wrapper provides state via context to the different pages. More from the [Gatsby docs](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement)

**Comment by gshorer97** [comment]
I see. This is quite interesting. TBH I didn't expect there to be much complexity with this feature but I'm glad that there are supported ways to deal with states across pages

**Comment by emilioziniades** [comment]
Yeah it is pretty cool - you can have multi page stateful websites that are basically applications 😁

**Comment by emilioziniades** [comment]
Have addressed this issue in commit 303279a698128d91e7989e49200cda7565128aa3 . The fix was actually pretty straightforward, just needed to do some digging in the Gatsby docs. If you are curious, the magic happens in `wrapRootElement`

**Comment by gshorer97** [comment]
This is great, the dApp feels a lot more congruent now
