### ISSUE TITLE
Claiming a new square seemingly claims 2 squares on the canvas

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#89]
When claiming a new square, the canvas updates the last 2 squares on the canvas with the chosen colour. While this is erroneous in itself, there are other strange behaviours related to this issue:
- Both squares appear to be owned. The first of the 2 squares is owned by the claimant while the second square is not.
- The history (correctly) only logs that the one square has been claimed

Claiming 2 squares seems to complicate the issue further:
_1. 1st square claim_
2. Square (n) and (n+1) change to the same selected colour. Square (n) is owned by claimant, square (n+1) is not
3. History (toast and table) only display **Square (n)** was claimed and changed
_4. 2nd square claim_
5. Square (n+2) and (n+3) change to the same selected colour. Square(n+2) is owned by claimant, square (n+3) is not
6. History (toast and table) only display that **Square (n+1)** was claimed and changed

So, the claiming logic seemingly works correctly. Within the canvas itself, there are errors with printing the squares as well as assigning correct ownership to these squares.

**Comment by emilioziniades** [comment]
Thanks man, good find. 

So this is what is happening, I think. 

When an individual claims a new square:

1. Transaction submitted to Ethereum network
2. Upon confirmation, app dispatches to state ('MINT')
3. A few moments later, event is emitted.
4. App, which is listening for event, then triggers a second dispatch ('MINT-REMOTE')

I think the second square you are seeing is due to the two dispatches ('MINT' and then 'MINT-REMOTE'). 

Basically these two dispatches should be mutually exclusive, Either someone else claims a square ('MINT-REMOTE' should dispatch), or you claim a square ('MINT' should dispatch).

Proposed solution: in the event listener in `app` , when a NewSquare event is emitted, the app will check if the visitor owns the square. If yes, the the state change has already been handled by 'MINT', and there is no need to dispatch 'MINT-REMOTE' too. If not, then dispatch 'MINT-REMOTE'

**Comment by emilioziniades** [comment]
Ok, so I have implemented the above fix (commit 4cd40176dbec7110b90f9cd13bee7a21d8d4d227), and I believe it's working correctly now. 

Closing this issue, but please re-open if it's still a problem.
