### ISSUE TITLE
Move changing colours and claiming squares UI to modals

### ISSUE THREAD

**Issue by gshorer97** [emilioziniades/flatland#90]
_This is more of a discussion based issue_

I propose that claiming a square and changing a squares colour should rather be performed in modal windows.

Motivations:
- When performing these actions the user should not really be interacting with other elements in the site
- The transaction taking place should be as clear as possible to the user 
- This will clean up the side panel and the manage squares table and free up space for future additions (square name, name change button, forfeit square button)
- Unifies the UX, limits component rerenders, and prevents weird CSS component size changes

How it would work for colour change:
- instead of the blank textbox and disabled button there will just be the change colour button
- On click, it will bring up the modal with the colour picker, an option to submit change and an option to cancel. Additionally, we can display the current colour of the square and perhaps text that tells the user "_*There is a small gas fee associated with colour changes_"
(This logic will be similar to name changes in the future)

How it would work for claiming squares:
- instead of the choose colour textbox there will just be the button to claim a square
- On click, it will bring up the modal with all the details of the square you want to claim as well as a form
- Currently, the form will just be the colour change textbox but in future can also have the square name and whatever else

**Comment by emilioziniades** [comment]
I think this is a great idea. It will also avoid all the bugs that are occuring in the canvas component at the moment.

Practically, this would entail: 

- [ ] Removing all this functionality out of canvas
- [ ] Creating a new modal component which makes use of the various forms
- [ ] Somehow give this component access to state (so that it knows which square is being claimed or changed) (either by passing it via props or context

Additional thoughts

- Currently, the loading animation is embedded into `baseForm` itself. But with this new approach, the user should confirm the transaction, and then have access to the rest of the site whilst they wait for the confirmation. It would be annoying to wait in the modal until the transaction is confirmed. We could then transfer the loading animation to a snackbar. We would then have three snackbars: yellow = loading, red = error and green = success

**Comment by gshorer97** [comment]
I have made some progress on this issue. Essentially, I have changed the baseForm slightly to use Modals. Still need to look into adding more information and context to each modal screen (show which square the user is interacting with and it's current properties)

I have added a processing transaction toast which gets replaced by the success or error toast once the transaction has been processed.

**Comment by gshorer97** [comment]
Form modals now are have more context to the index square. I am closing this issue.
